import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-center bg-gray-100">
          <div className="min-h-screen w-[min(520px,100vw)] bg-white pt-4 pb-28 px-4">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
